
stripe.secret.Key=YOUR_STRIPE_SECRET_KEY
stripe.webhook.secret=YOUR_WEBHOOK_SECRET

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jwt.secretKey=${JWT_SECRETKEY}
